---
- name: Drop corosync.conf
  template:
    src: "corosync.conf.j2"
    dest: "/etc/corosync/corosync.conf"
    backup: True
    owner: root
    group: root
    mode: "0644"
  notify: restart corosync

- name: Enabled corosync service
  replace:
    dest: "/etc/default/corosync"
    regexp: "^START\ ?=\ ?no"
    replace: "START=yes"
    backup: True

- name: append START
  lineinfile: 
    #ansible version < 2.3
    dest: /etc/default/corosync
    #ansible version >= 2.3
    #path: /etc/default/corosync 
    insertafter: EOF
    line: "START=yes" 
    state: present


#- name: append START
#  shell: "sed -i '$a START=yes' /etc/default/corosync"

#- name: restart corosync
#  notify: 
#  - restart corosync

- meta: flush_handlers
