---
- name: download haproxy agents
  get_url:
    url: https://raw.githubusercontent.com/thisismitch/cluster-agents/master/haproxy
    dest: /usr/lib/ocf/resource.d/heartbeat/haproxy
    force: yes

- name: add execute right
  file: path=/usr/lib/ocf/resource.d/heartbeat/haproxy mode=a+x

#- name: chmod x
#  shell: chmod +x /usr/lib/ocf/resource.d/heartbeat/haproxy
