---
- name: download haproxy agents
  get_url:
    url: "{{ cluster_agent_haproxy_url }}"
    dest: "{{ cluster_agent_dest }}"
    force: yes

- name: add execute right
  file: path={{ cluster_agent_dest }} mode=a+x

#- name: chmod x
#  shell: chmod +x /usr/lib/ocf/resource.d/heartbeat/haproxy
