---
- name: install corosync & pacemaker packages
  apt:
    name: "{{ item }}"
    state: "latest"
  with_items: "{{ corosync_pacemaker_apt_packages }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2